### PR TITLE
Lesson 35 - Missing MenuItemStyles and Order.js changes

### PR DESCRIPTION
**Pull request by break7533**
Hi there,

I noticed that some files were missing from the stepped solutions.

Especially the CSS is a nice to have uploaded.

### CODE REVIEW

**Comment by wesbos** [comment]
@Asjas can you check if this is needed?

**Comment by Asjas** [comment]
Yeah I'll check and let you know 🙂

**Comment by Asjas** [comment]
Yeah @wesbos, I see both those files are changed in lesson 35 and that they are missing from the stepped solutions 👍

**Comment by wesbos** [comment]
Thanks both of you

**Pull request merged**
